####
# 
# Author: Toby Patterson
# File: plot2.R
# Date: 7 August 2014
#
# Plots the relationship between days of week and Global Active Power (in kilowatts)
# Presumes the file household_power_consumption.txt exists in the same directory.
#
####

## Read in the table data
power = read.table(
  file='household_power_consumption.txt',
  sep=';',
  header=T,
  colClasses=c('character','character','numeric','numeric','numeric','numeric','numeric','numeric','numeric'),
  na.strings=c("NA", "?")
  #,nrows=10000
)

## Convert dates and subset for range 
date_format = "%d/%m/%Y"
power$DateTime = strptime(paste(power$Date, power$Time), format = "%d/%m/%Y %H:%M:%S")
power$Date = as.Date(power$Date, date_format)
data = subset(
  power,
  Date >= as.Date('01/02/2007', date_format) & Date < as.Date('03/02/2007', date_format)
)

# Output to file
canvas_size = 480
png( 
  file="plot2.png",
  height = canvas_size, 
  width=canvas_size
)
plot(
  data$DateTime,
  data$Global_active_power, 
  ylab='Global Active Power (kilowatts)',
  xlab='',
  type='l'
)

# Yes I do want this
mtext('generated by Toby Patterson, 7 Sept 2014',1,4,cex=.5)

# Detatch
dev.off()

