####
# 
# Author: Toby Patterson
# File: plot1.R
# Date: 7 August 2014
#
# Create a basic histogram showing the frequency of Global Active Power (in kilowatts).
# Presumes the file project1_datafile.Rda exists in the same directory.
#
####

## Read in the table data
power = load('project1_datafile.Rda')

# Plot the relationship
canvas_size = 480
png( 
  file="plot1.png",
  height = canvas_size, 
  width=canvas_size
)
hist(
  data$Global_active_power, 
  main='Global Active Power',
  xlab='Global Active Power (kilowatts)',
  col='red'
)

# Yes I do want this
mtext('generated by Toby Patterson, 7 Sept 2014',1,4,cex=.5)

# Detatch
dev.off()

