####
# 
# Author: Toby Patterson
# File: plot3.R
# Date: 7 August 2014
#
# Plots the relationship between days of week and various Energy sub metering.
# Presumes the file project1_datafile.Rda exists in the same directory.
#
####

## Read in the table data
power = load('project1_datafile.Rda')

# Output to file
canvas_size = 480
png( 
  file="plot3.png",
  height = canvas_size, 
  width=canvas_size
)
plot(
  data$DateTime,
  data$Sub_metering_1,
  #ylim=c(1,max(apply(data[,c("Sub_metering_1","Sub_metering_2","Sub_metering_3")], 2, max))),
  ylab='Energy sub metering',
  xlab='',
  type='n'
)

# Plot points
points(data$DateTime,data$Sub_metering_1,col='black',type='l')
points(data$DateTime,data$Sub_metering_2,col='red',type='l')
points(data$DateTime,data$Sub_metering_3,col='blue',type='l')

legend("topright",
  col=c("black", "red", "blue"),
  c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),
  lty=1
)

# Yes I do want this
mtext('generated by Toby Patterson, 7 Sept 2014',1,4,cex=.5)

# Detatch
dev.off()

