####
# 
# Author: Toby Patterson
# File: plot1.R
# Date: 7 August 2014
#
# Create a basic histogram showing the frequency of Global Active Power (in kilowatts).
# Presumes the file household_power_consumption.txt exists in the same directory.
#
####

## Read in the table data
power = read.table(
  file='household_power_consumption.txt',
  sep=';',
  header=T,
  colClasses=c('character','character','numeric','numeric','numeric','numeric','numeric','numeric','numeric'),
  na.strings=c("NA", "?")
  #,nrows=100000
)

## Convert dates and subset for 
date_format = "%d/%m/%Y"
power$Date = as.Date(as.character(power$Date), date_format)
data = subset(
  power,
  Date >= as.Date('01/02/2007', date_format) & Date < as.Date('03/02/2007', date_format)
)

# Plot the relationship
canvas_size = 480
png( 
  file="plot1.png",
  height = canvas_size, 
  width=canvas_size
)
hist(
  data$Global_active_power, 
  main='Global Active Power',
  xlab='Global Active Power (kilowatts)',
  col='red'
)

# Yes I do want this
mtext('generated by Toby Patterson, 7 Sept 2014',1,4,cex=.5)

# Detatch
dev.off()

