####
# 
# Author: Toby Patterson
# File: plot2.R
# Date: 7 August 2014
#
# Plots the relationship between days of week and Global Active Power (in kilowatts)
# Presumes the file project1_datafile.Rda exists in the same directory.
#
####

## Read in the table data
power = load('project1_datafile.Rda')

# Output to file
canvas_size = 480
png( 
  file="plot2.png",
  height = canvas_size, 
  width=canvas_size
)
plot(
  data$DateTime,
  data$Global_active_power, 
  ylab='Global Active Power (kilowatts)',
  xlab='',
  type='l'
)

# Yes I do want this
mtext('generated by Toby Patterson, 7 Sept 2014',1,4,cex=.5)

# Detatch
dev.off()

