####
# 
# Author: Toby Patterson
# File: plot3.R
# Date: 7 August 2014
#
# Plots the relationship between days of week and various Energy sub metering.
# Presumes the file household_power_consumption.txt exists in the same directory.
#
####

## Read in the table data
power = read.table(
  file='household_power_consumption.txt',
  sep=';',
  header=T,
  colClasses=c('character','character','numeric','numeric','numeric','numeric','numeric','numeric','numeric'),
  na.strings=c("NA", "?")
  #,nrows=10000
)

## Convert dates and subset for range 
date_format = "%d/%m/%Y"
power$DateTime = strptime(paste(power$Date, power$Time), format = "%d/%m/%Y %H:%M:%S")
power$Date = as.Date(power$Date, date_format)
data = subset(
  power,
  Date >= as.Date('01/02/2007', date_format) & Date < as.Date('03/02/2007', date_format)
)

# Output to file
canvas_size = 480
png( 
  file="plot3.png",
  height = canvas_size, 
  width=canvas_size
)
plot(
  data$DateTime,
  data$Sub_metering_1,
  #ylim=c(1,max(apply(data[,c("Sub_metering_1","Sub_metering_2","Sub_metering_3")], 2, max))),
  ylab='Energy sub metering',
  xlab='',
  type='n'
)

# Plot points
points(data$DateTime,data$Sub_metering_1,col='black',type='l')
points(data$DateTime,data$Sub_metering_2,col='red',type='l')
points(data$DateTime,data$Sub_metering_3,col='blue',type='l')

legend("topright",
  col=c("black", "red", "blue"),
  c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),
  lty=1
)

# Yes I do want this
mtext('generated by Toby Patterson, 7 Sept 2014',1,4,cex=.5)

# Detatch
dev.off()

